spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:~/test;DB_CLOSE_DELAY=-1;INIT=RUNSCRIPT FROM 'classpath:init.sql';
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2


  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

app:
  margin: 2

